repos:
- repo: local
  hooks:
    - id: increment-version
      name: increment-version
      entry: git-hooks/pre-commit/increment-version.ps1
      language: script
      verbose: true
      files: '.pre-commit-config.yaml' # Makes the script run
      always_run: true                 # once on each commit