default_install_hook_types: [pre-commit, pre-push, commit-msg]
repos:
- repo: local
  hooks:
    - id: increment-version
      name: increment-version
      entry: git-hooks/pre-commit/increment-version.ps1
      language: script
      verbose: true
      stages: [commit-msg] # The script will be given a filepath to file with commit message
      always_run: true     # Makes the script run once on each commit